FROM  maven:3.8.6-eclipse-temurin-11 as builder
# add pom.xml and source code
ADD ./pom.xml pom.xml
RUN mvn dependency:go-offline
ADD ./src src/
RUN mvn clean install -Pbatch -DskipTests --batch-mode

FROM eclipse-temurin:11-jre
ARG JAR_VERSION=2.5.0
RUN mkdir -p /app
WORKDIR /app
ENV OUTPUT_DIR=/parquet
COPY --from=builder target/flink-jobs-${JAR_VERSION}-etl-export.jar etl-export.jar
ADD parquet-export.sh ./parquet-export.sh
CMD [ "/bin/sh","/app/parquet-export.sh" ]
