FROM  maven:3.8.6-eclipse-temurin-11 as builder
# add pom.xml and source code
ADD ./pom.xml pom.xml
RUN mvn dependency:go-offline
ADD ./src src/
RUN mvn clean install -Pbatch

FROM eclipse-temurin:11-jre
ARG JAR_VERSION=2.2.0-SNAPSHOT
RUN mkdir -p /app
WORKDIR /app
COPY --from=builder target/flink-jobs-${JAR_VERSION}-etl-batch.jar etl-batch.jar
ADD batch-etl.sh ./batch-etl.sh
RUN chmod +x ./batch-etl.sh
CMD [ "/bin/sh","/app/batch-etl.sh" ]
