FROM  maven:3.8.6-eclipse-temurin-8 as builder
# add pom.xml and source code
ADD ./pom.xml pom.xml
RUN mvn dependency:go-offline
ADD ./src src/
RUN mvn clean install -Pbatch

FROM eclipse-temurin:8-jre
ENV OUTPUT_DIR=/parquet
COPY --from=builder target/ozone-etl-flink-1.0-SNAPSHOT-etl-export.jar etl-export.jar
COPY --from=builder target/ozone-etl-flink-1.0-SNAPSHOT-etl-migrations.jar /opt/flink/usrlib/ozone-etl-migrations.jar
ADD ./batch-export.sh ./batch-export.sh
COPY run.sh /run.sh
RUN chmod +x /run.sh
CMD [ "/bin/sh","./batch-export.sh" ]
