FROM  maven:3.8.6-eclipse-temurin-11 as builder

ENV MAVEN_OPTS="-Xmx2g"

# Copy pom.xml and source code
COPY ./pom.xml pom.xml
COPY ./src src/

RUN mvn clean install -Pbatch -DskipTests --batch-mode

FROM eclipse-temurin:11-jre
ARG JAR_VERSION=2.2.0-SNAPSHOT
RUN mkdir -p /app
WORKDIR /app
COPY --from=builder target/flink-jobs-${JAR_VERSION}-etl-batch.jar etl-batch.jar
ADD batch-etl.sh ./batch-etl.sh
RUN chmod +x ./batch-etl.sh
CMD [ "/bin/sh","/app/batch-etl.sh" ]
