CREATE TABLE `patient_programs` (
    `patient_program_id` BIGINT,
    `patient_id` BIGINT,
    `program_id` BIGINT,
    `date_enrolled` TIMESTAMP,
    `date_completed` TIMESTAMP,
    `location_id` BIGINT,
    `outcome_concept_id` BIGINT,
    `creator` BIGINT,
    `date_created` TIMESTAMP,
    `changed_by` BIGINT,
    `date_changed` TIMESTAMP,
    `voided` BOOLEAN,
    `voided_by` BIGINT,
    `date_voided` TIMESTAMP,
    `void_reason` VARCHAR,
    `uuid` VARCHAR,
    `program_retired` BOOLEAN,
    `program_name` VARCHAR,
    `program_description` VARCHAR,
    `program_uuid` VARCHAR,
    `program_concept_id` BIGINT,
    `concept_name` VARCHAR,
    `concept_uuid` VARCHAR,
    `program_outcomes_concept_id` BIGINT,
    `outcomes_concept_name` VARCHAR,
    `outcomes_concept_uuid` VARCHAR
)