CREATE TABLE `conditions` (
    `condition_id` BIGINT,
    `additional_detail` VARCHAR,
    `previous_version` BIGINT,
    `condition_coded` BIGINT,
    `condition_non_coded` VARCHAR,
    `condition_coded_name` BIGINT,
    `clinical_status` VARCHAR,
    `verification_status` VARCHAR,
    `onset_date` TIMESTAMP,
    `date_created` TIMESTAMP,
    `voided` BOOLEAN,
    `date_voided` TIMESTAMP,
    `void_reason` VARCHAR,
    `uuid` VARCHAR,
    `creator` BIGINT,
    `voided_by` BIGINT,
    `changed_by` BIGINT,
    `patient_id` BIGINT,
    `end_date` TIMESTAMP
)