#!/usr/bin/env python3
"""Generates the development source-database schemas from the Flink table definitions.

The flattening jobs declare each source table as a Flink DDL (the ANALYTICS_SOURCE_TABLES_PATH
files). Those declare the exact columns the pipelines read, so the development databases are
derived from them rather than maintained by hand -- a hand-written copy silently drifts, and the
first symptom is a job failing at submission on a missing column.

Usage:  generate-schemas.py <flattening/tables dir> <output dir>
"""
import re
import sys
from pathlib import Path

# Flink type -> (MariaDB, PostgreSQL). VARCHAR needs an explicit length on MariaDB; CHAR is only
# ever used for OpenMRS uuid columns, which are char(38).
TYPES = {
    "INT": ("INT", "INTEGER"),
    "INTEGER": ("INT", "INTEGER"),
    "TINYINT": ("TINYINT", "SMALLINT"),
    "VARCHAR": ("VARCHAR(255)", "VARCHAR"),
    "CHAR": ("CHAR(38)", "CHAR(38)"),
    "BOOLEAN": ("TINYINT(1)", "BOOLEAN"),
    "TIMESTAMP": ("DATETIME", "TIMESTAMP"),
    "DATE": ("DATE", "DATE"),
    "TIME": ("TIME", "TIME"),
    "DOUBLE": ("DOUBLE", "DOUBLE PRECISION"),
    "NUMERIC": ("DECIMAL(18,6)", "NUMERIC"),
    "DECIMAL": ("DECIMAL(18,6)", "NUMERIC"),
}

# Identifiers are optionally back-quoted: most DDLs quote them, obs.sql does not. Requiring the
# quotes silently produces a table with no columns rather than an error, so keep them optional.
COLUMN = re.compile(r"`?(?P<name>\w+)`?\s+(?P<type>[A-Za-z]+)", re.I)
PRIMARY_KEY = re.compile(r"PRIMARY\s+KEY\s*\((?P<cols>[^)]+)\)", re.I)


def parse(ddl: str):
    """Returns (columns, primary_key_columns) from a Flink CREATE TABLE."""
    body = ddl[ddl.index("(") + 1 : ddl.rindex(")")]
    columns, pk = [], []
    for line in body.splitlines():
        line = line.strip().rstrip(",")
        if not line:
            continue
        if line.upper().startswith("PRIMARY KEY"):
            m = PRIMARY_KEY.search(line)
            if m:
                pk = [c.strip(" `") for c in m.group("cols").split(",")]
            continue
        m = COLUMN.match(line)
        if m:
            columns.append((m.group("name"), m.group("type").upper()))
    return columns, pk


def render(table: str, columns, pk, dialect: int, quote: str) -> str:
    # A parse that matches nothing would otherwise emit `CREATE TABLE x ()`, which is invalid SQL
    # at best and an empty table at worst. Fail instead.
    if not columns:
        raise SystemExit(f"{table}: no columns parsed from its Flink DDL")
    if not pk:
        raise SystemExit(f"{table}: no PRIMARY KEY parsed; CDC and upserts both need one")
    lines = []
    for name, flink_type in columns:
        if flink_type not in TYPES:
            raise SystemExit(f"{table}.{name}: unmapped Flink type {flink_type!r}")
        lines.append(f"  {quote}{name}{quote} {TYPES[flink_type][dialect]}")
    if pk:
        keys = ", ".join(f"{quote}{c}{quote}" for c in pk)
        lines.append(f"  PRIMARY KEY ({keys})")
    return f"CREATE TABLE IF NOT EXISTS {quote}{table}{quote} (\n" + ",\n".join(lines) + "\n);"


def main():
    tables_dir, out_dir = Path(sys.argv[1]), Path(sys.argv[2])

    # Each database gets its own init directory: docker-entrypoint-initdb.d runs everything it
    # is given, so a shared directory would feed the MariaDB schema to PostgreSQL and vice versa.
    for source, dialect, quote, out_name in (
        ("openmrs", 0, "`", "mariadb/01-openmrs-schema.sql"),
        ("odoo", 1, '"', "postgres/02-odoo-schema.sql"),
    ):
        src = tables_dir / source
        statements = []
        for path in sorted(src.glob("*.sql")):
            columns, pk = parse(path.read_text())
            statements.append(render(path.stem, columns, pk, dialect, quote))

        header = (
            f"-- GENERATED by development/seed/generate-schemas.py from the {source} Flink table\n"
            f"-- definitions. Do not edit by hand; re-run the generator instead.\n"
            f"--\n"
            f"-- These are the {source} source tables the flattening pipelines read. Only the columns\n"
            f"-- the pipelines actually use are present, so this is not a full {source} schema.\n"
            f"-- No foreign keys: Debezium does not need them, and they would impose an insert\n"
            f"-- order on the sample data for no benefit.\n\n"
        )
        target = out_dir / out_name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(header + "\n\n".join(statements) + "\n")
        print(f"  {out_name}: {len(statements)} tables")


if __name__ == "__main__":
    main()
