CREATE TABLE `location` (
  `location_id` int,
  `name` VARCHAR,
  `description` VARCHAR,
  `address1` VARCHAR,
  `address2` VARCHAR,
  `city_village` VARCHAR,
  `state_province` VARCHAR,
  `postal_code` VARCHAR,
  `country` VARCHAR,
  `latitude` VARCHAR,
  `longitude` VARCHAR,
  `creator` int,
  `date_created` TIMESTAMP,
  `county_district` VARCHAR,
  `address3` VARCHAR,
  `address4` VARCHAR,
  `address5` VARCHAR ,
  `address6` VARCHAR ,
  `retired` BOOLEAN ,
  `retired_by` int ,
  `date_retired` TIMESTAMP ,
  `retire_reason` VARCHAR ,
  `parent_location` int ,
  `uuid` char,
  `changed_by` int ,
  `date_changed` TIMESTAMP ,
  `address7` VARCHAR ,
  `address8` VARCHAR ,
  `address9` VARCHAR ,
  `address10` VARCHAR ,
  `address11` VARCHAR ,
  `address12` VARCHAR ,
  `address13` VARCHAR ,
  `address14` VARCHAR,
  `address15` VARCHAR ,
  PRIMARY KEY (`location_id`) NOT ENFORCED
)