CREATE TABLE `orders` (
  `order_id` int,
  `order_type_id` int,
  `concept_id` int,
  `orderer` int,
  `encounter_id` int,
  `instructions` VARCHAR,
  `date_activated` TIMESTAMP,
  `auto_expire_date` TIMESTAMP,
  `date_stopped` TIMESTAMP,
  `order_reason` int,
  `order_reason_non_coded` VARCHAR,
  `creator` int,
  `date_created` TIMESTAMP,
  `voided` BOOLEAN,
  `voided_by` int,
  `date_voided` TIMESTAMP,
  `void_reason` VARCHAR,
  `patient_id` int,
  `accession_number` VARCHAR,
  `uuid` char(38) NOT NULL,
  `urgency` VARCHAR,
  `order_number` VARCHAR,
  `previous_order_id` int,
  `order_action` VARCHAR,
  `comment_to_fulfiller` VARCHAR,
  `care_setting` int,
  `scheduled_date` TIMESTAMP,
  `order_group_id` int,
  `sort_weight` DOUBLE,
  `fulfiller_comment` VARCHAR,
  `fulfiller_status` VARCHAR,
  `form_namespace_and_path` VARCHAR,
  PRIMARY KEY (`order_id`) NOT ENFORCED
)