CREATE TABLE `patient_appointment` (
  `patient_appointment_id` int,
  `provider_id` int,
  `appointment_number` VARCHAR,
  `patient_id` int,
  `start_date_time` TIMESTAMP,
  `end_date_time` TIMESTAMP,
  `appointment_service_id` int,
  `appointment_service_type_id` int,
  `status` VARCHAR,
  `location_id` int,
  `appointment_kind` VARCHAR,
  `comments` VARCHAR,
  `uuid` VARCHAR,
  `date_created` TIMESTAMP,
  `creator` int,
  `date_changed` TIMESTAMP,
  `changed_by` int,
  `voided` BOOLEAN,
  `voided_by` int,
  `date_voided` TIMESTAMP,
  `void_reason` VARCHAR,
  `related_appointment_id` int,
  `tele_health_video_link` VARCHAR,
  PRIMARY KEY (`patient_appointment_id`) NOT ENFORCED
)